training: !!bool "true"  # string --> bool
unprocessed_data: '../data/TIMIT_Transformed/*/*/*/*.WAV'

---
data:

  data_preprocessed: !!bool "true"

  train_path_unprocessed: '../data/TIMIT_Transformed/train_wav/*/*/*.WAV'
  test_path_unprocessed: '../data/TIMIT_Transformed/test_wav/*/*/*.WAV'
  train_path: '../data/TIMIT_preprocessed/train_tisv2'
  test_path: '../data/TIMIT_preprocessed/test_tisv2'

  sr: 16000
  tisv_frame: 180
  len_frame: 0.025
  hop_frame: 0.01
  nfft: 512
  nmels: 40
  train_speaker: 567
  test_speaker: 63
---
model:
  lstm_hidden: 64
  num_layer:  1
  linear_hidden: 128
  #model_path
---
train:
  num_utters: 10
  batch_size: 6
  lr: 0.01
  epochs: 300
---
test:
  num_utters: 6
  batch_size: 4
